### ISSUE TITLE
Missing riscv64-unknown-linux-gnu-gdb

### ISSUE THREAD

**Issue by realShengYao** [aosp-riscv/test-riscv#2]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/30943636/160270064-b6d0e04d-c9a8-4ddd-811e-c4ceca190644.png">
Here when I try to enable the DEBUG mode of the run.sh in host, it can't find riscv64-unknown-linux-gnu-gdb.

**Comment by unicornx** [comment]
resolved by https://gitee.com/aosp-riscv/test-riscv/pulls/16
